version: '3.3'

services:
  visual:
    image: graph_test:latest
    build: .
    container_name: graph_visual
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"